<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WaitBehaviour\Abstract\AbstractWaitBehaviour.cs" Link="WaitBehaviour\Abstract\AbstractWaitBehaviour.cs" />
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WaitBehaviour\WaitBehaviourLinux.cs" Link="WaitBehaviour\WaitBehaviourLinux.cs" />
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WaitBehaviour\WaitBehaviourNone.cs" Link="WaitBehaviour\WaitBehaviourNone.cs" />
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WaitBehaviour\WaitBehaviourWindows.cs" Link="WaitBehaviour\WaitBehaviourWindows.cs" />
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WebService\Abstract\AbstractEasyWebService.cs" Link="WebService\Abstract\AbstractEasyWebService.cs" />
    <Compile Include="..\IDS.Lexik.WebService.Sdk\WebService\Configuration\EasyWebServiceConfiguration.cs" Link="WebService\Configuration\EasyWebServiceConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Projekte-Kooperation\TfresWebserver\TFRES.DotNet5\TFRES.DotNet5.csproj" />
    <ProjectReference Include="..\..\..\CorpusExplorerV2\CorpusExplorer\BitCutStudios.CorpusExplorer\BitCutStudios.CorpusExplorer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="WaitBehaviour\Abstract\" />
    <Folder Include="WebService\Abstract\" />
    <Folder Include="WebService\Configuration\" />
  </ItemGroup>

</Project>
